[package]
name = "idmangler-lib"
description = "Library for encoding and decoding Wynntils id strings"
authors = ["Zatzou"]
repository = "https://github.com/Zatzou/idmangler-lib"
readme = "readme.md"
license = "LGPL-3.0"
version = "0.1.1"
edition = "2021"

[dependencies]
thiserror = "1.0"
